const EMPLOYEES = [

"Drs.STEFANUS TRIADI ATMONO, M.Si.",
"Drs. AGUNG WIDODO",
"DWIANA HANDAYANI,SE",
"EDY PURWANTO, SE",
"Bakti Dwi Prasetyo, S.T., M.T.",
"SUDARSONO",
"ANIKMATUL KHOIRIYAH, S.M.",
"RENY YANTI, S.Pd",
"RIZAL RIZKIANTO, A.Md"

]
